name: Validate 

on:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: setup terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Format check
          working-directory: ./infra
          run: terraform fmt -check -recursive 

        - name: Terraform Init
          working-directory: ./infra
          run: terraform init -backend=false

        - name: Terraform Validate
          working-directory: ./infra
          run: terraform validate
        
        - name: setup TFLint
          uses: terraform-linters/setup-tflint@v4

        - name: Initialize TFLint
          working-directory: ./infra
          run: tflint --init

        - name: run TFLint
          working-directory: ./infra
          run: tflint 


        
